version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: usis-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: USIS_Project
      MYSQL_USER: usis_user
      MYSQL_PASSWORD: usis_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
