jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437 # Example 256-bit secret
  expiration: 86400000 # 24 hours

spring:
  web:
    resources:
      static-locations: classpath:/frontend/,classpath:/static/
  datasource:
    url: jdbc:sqlserver://192.168.1.19:1433;databaseName=USIS_Project;encrypt=true;trustServerCertificate=true;
    username: webServer
    password: webServer123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
