jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

spring:
  datasource:
    url: jdbc:mysql://project-db.cgwwvoqqy7bq.us-east-1.rds.amazonaws.com:3306/USIS_Project?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: usisDB123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


docker run -d --name usis-backend -p 8080:8080 \
  -e SPRING_DATASOURCE_URL="jdbc:mysql://project-db.cgwwvoqqy7bq.us-east-1.rds.amazonaws.com:3306/USIS_Project" \
  -e SPRING_DATASOURCE_USERNAME="admin" \
  -e SPRING_DATASOURCE_PASSWORD="usisDB123" \
  jasonow/usis-backend:v1