jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437 # Example 256-bit secret
  expiration: 86400000 # 24 hours

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/USIS_Project?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: usis_user
    password: usis_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update